### ISSUE TITLE
How load marathon module?

### ISSUE THREAD

**Issue by kikicarbonell** [udacity/ansible-marathon#4]

**Comment by earldouglas** [comment]
This module is not (yet) distributed with Ansible, so you need to download it (e.g. `git clone git@github.com/udacity/ansible-marathon` or grab and extract https://github.com/udacity/ansible-marathon/archive/master.zip), and tell ansible where to find it with `-M`:

```
$ ansible-playbook -i inventory.ini -M /path/to/ansible-marathon playbook.yml
```

**Comment by kikicarbonell** [comment]
I'm trying as you say, but don't work:

My command:
`ansible-playbook -i inventory.ini -M /roleproject/ansible-marathon playbook.yml`
The result:
`ERROR: marathon is not a legal parameter of an Ansible Play`

**Comment by earldouglas** [comment]
Can you provide a directory listing of _/roleproject/ansible-marathon_, and the `marathon` section of your _playbook.yml_?

**Comment by kikicarbonell** [comment]
OK, my files:
**inventory.ini**

```
localhost ansible_connection=local
```

**playbook.yml**

```
- name: Deploy to Marathon
  marathon:
    marathon_uri: https://localhost:8080/
    app_id: nodejs-rest-api
    app_json: "{{ lookup('file', '/roleproject/app.json') }}"

```

Command `ls -all on /roleproject`

```
drwxrwxr-x  3 1000 1000 4096 Feb 29 16:32 .
drwxr-xr-x 82 root root 4096 Feb 29 16:34 ..
drwxrwxr-x  3 1000 1000 4096 Feb 29 16:32 ansible-marathon
-rw-rw-r--  1 1000 1000  229 Feb 25 16:14 app.json
-rw-rw-r--  1 1000 1000   35 Feb 29 16:31 inventory.ini
-rw-rw-r--  1 1000 1000  171 Feb 29 16:32 playbook.yml

```

**Comment by earldouglas** [comment]
Hmm, I'm stumped.  That all looks correct to me.  What version of Ansible are you running?  `ansible-playbook --version`

**Comment by kikicarbonell** [comment]
1.9.4

**Comment by earldouglas** [comment]
Is the `marathon` section in your _playbook.yml_ is under a `tasks` section?

**Comment by cjw296** [comment]
@earldouglas - could this be packaged up and put on pypi? 
(sorry if that's a silly suggestion, not sure I understand the ansible ecosystem with respect to new modules yet...)

**Comment by earldouglas** [comment]
@cjw296 That's a very interesting idea; I'll look into it.  See https://github.com/udacity/ansible-marathon/issues/5 for updates.

**Comment by earldouglas** [comment]
@kkdevops I think this might be an error in your _playbook.yml_ file.  Can you convirm that it includes `hosts` and `tasks` sections?

``` yaml
- hosts: localhost

  tasks:

  - name: Deploy to Marathon
    marathon:
      marathon_uri: https://localhost:8080/
      app_id: nodejs-rest-api
      app_json: "{{ lookup('file', '/roleproject/app.json') }}"
```
